### ISSUE TITLE
[github] add CLI check for PRs

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/sprotty-theia#17]
Seems to be missing

**Comment by spoenemann** [comment]
What exactly is missing?

**Comment by JanKoehnlein** [comment]
If it's there now, feel free to close this.

**Comment by JanKoehnlein** [comment]
Sorry, I mean ECA check. The one that makes sure that the committer has signed the ECA and that is run as a check on the GH PR.

**Comment by spoenemann** [comment]
That one is active, see e.g. https://github.com/eclipse/sprotty-theia/pull/28 (click on the green check mark beneath the commit hash).
