### ISSUE TITLE
Context menu entry "Open in Diagram" should be in own category

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/sprotty-theia#34]
The editor context menu entry "Open in Diagram" is registered without any sub-category, see
https://github.com/eclipse/sprotty-theia/blob/7e2c221b38ecac64a003af2a05b39d911a0ac0e7/src/theia/diagram-commands.ts#L66
and
https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-menu.ts

That causes the "Open in Diagram" to be added in the context menu without any separator in the Cut/Copy/Paste group, where it does not belong to.

It should be added to a new group, so a separator is shown between the groups.

![OpenInDiagramContext](https://user-images.githubusercontent.com/47597619/55481591-0472fe80-5623-11e9-9455-77c3b158a19c.png)

**Comment by JanKoehnlein** [comment]
PRs are welcome
