### ISSUE TITLE
Switch dependencies back to next?

### ISSUE THREAD

**Issue by tortmayr** [eclipse/sprotty-theia#58]
For the 0.8.0 release the dependencies for sprotty/theia got changed from "next" to a fixed version. 
Should we change them back to "next" now? Otherwise unreleased changes from sprotty or theia cannot be consumed here. (Like it has been done after the 0.7.0 release 861a04393b1f24816f1623e88d86dd8d2147c298)

**Comment by spoenemann** [comment]
The dependency to `sprotty` should go back to `next`, but I'd prefer to keep a fixed version for Theia. Using next versions often brings problems.
