### ISSUE TITLE
sprotty-theia only meant for "latest" Theia apps?

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse/sprotty-theia#60]
Latest "next" release contains dependencies to Theia "latest"

version: 0.9.0-next.72ba049

`package.json` contains solid revisions of depended-upon Theia extensions : 

```
"dependencies": {
    "@theia/core": "1.0.0",
    "@theia/editor": "1.0.0",
    "@theia/filesystem": "1.0.0",
    "@theia/languages": "1.0.0",
    "@theia/monaco": "1.0.0",
    "sprotty": "next"
  }
```

This makes this extension unsuitable to be included in a `next` Theia application - mixing `latest` and `next` can sometimes build, but the app fails to start at runtime. 

Maybe this is intended? i.e. the way "next" is used seems to apply only to `sprotty` - effectively it's still a `latest` extension as far as Theia is concerned, which can be confusing.

**Comment by spoenemann** [comment]
See #61: Using `^1.0.0` both in `latest` and `next` releases could resolve the problems?

**Comment by marcdumais-work** [comment]
For `latest` releases of `sprotty-theia` I think we're ok with the proposal in #61. But I do not think that will be enough for `next` releases. The Theia dependencies listed above would need to be exactly `next` think.
