### ISSUE TITLE
Q: using sprotty-theia in Theia apps

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse/sprotty-theia#61]
From the repo's readme it looks like what's wanted it to have each release of `sprotty-theia` mapping to one specific supported Theia release, rather than to try to support `latest`. 

Latest sprotty-theia (v0.8.0) looks to map to Theia v1.0.0. I have been able to make my app compile and work, but I had to:
- depend on Theia platform extensions `1.0.0` for all Theia platform extensions mentioned in `dependencies` of my app's `package.json`
- bolt-down versions of all Theia platform extensions to `1.0.0` by using a `resolutions` block in my app's `package.json`

Is there a better way?

**Comment by spoenemann** [comment]
We could loosen the Theia dependency to `^1.0.0` and hope for sufficient stability of the relevant APIs.

**Comment by marcdumais-work** [comment]
I think this would help. Worst case we're back to using resolutions to pin an earlier version, if latest has APIs that cause issues.

**Comment by spoenemann** [comment]
Fixed with https://github.com/eclipse/sprotty-theia/commit/b9c85a28cd82d91461ba02ef3030cd3ddfeac5b2
