### ISSUE TITLE
Theia 1.5.0 support for sprotty?

### ISSUE THREAD

**Issue by Samridhiseth** [eclipse/sprotty-theia#67]
how to integrate sprotty with theia 1.5.0 as its depenendency?

**Comment by spoenemann** [comment]
We will have to change a lot of things because Theia is ending support for integrating language servers directly. Probably this means reimplementing the whole LSP-specific part in `sprotty-theia`.

CC @JanKoehnlein

**Comment by JanKoehnlein** [comment]
The recommended way to connect to language servers from Theia will be via VS Code extensions. I think we should deprecate the LSP stuff in sprotty-theia entirely in favor of sprotty-vscode.

**Comment by tortmayr** [comment]
Hi, what is the status of this issue? Is somebody actively working on this?

**Comment by tortmayr** [comment]
Hi, what is the status of this issue? 
Eclipse GLSP reuses (the non-lsp related stuff) of `sprotty-theia` so we are currently not able to support Theia >1.4.0. 
Is somebody already working on this?

**Comment by spoenemann** [comment]
No, not yet. I'm not sure whether it's possible to have a deprecation cycle about this and still update to Theia > 1.4.0. Maybe the only solution is to drop everything LSP-related now.

**Comment by tortmayr** [comment]
I agree, unfortunately I think the only options is to drop everything LSP-related so that we can get rid of the `@theia/languages` dependency.

**Comment by JanKoehnlein** [comment]
Yes, we have to drop the LSP stuff. It's continued in sprotty-eclipse, and users have to migrate to that anyway, as Theia supports LSP only by VS Code extensions now.

I still have like 20 reads per week of my medium blogpost on the xtext-theia-sprotty example which makes heavy use of this stuff. I'll probably write another one after EclipseCon covering the same topic with VS Code extensions. If anybody volunteered to remove the LSP stuff here, I'd welcome if we could wait with the merge until that blogpost is on, such that users do have an alternative way of doing things they did with sprotty-theia.

**Comment by JanKoehnlein** [comment]
The [article](https://www.typefox.io/blog/domain-specific-languages-in-theia-and-vs-code) is out. Feel free to remove the LSP parts.
